from tests.compiler.punkt_compiler_test_helper import PunktCompilerTestHelper

class TestRational(object):
  """ Rational type test suite. """

  def setup_class(self):
    self._compile_helper = PunktCompilerTestHelper()

  def test_good_rational_1(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_2(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_3(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_4(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_5(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_6(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_7(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_8(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_9(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_10(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_11(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_12(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_13(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)
  
  def test_good_rational_14(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_15(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

  def test_good_rational_16(self):
    try:
      actual_output_path = self._compile_helper.compile_with_success()
      self._compile_helper.verify_actual_output(actual_output_path)
    except RuntimeError as ex:
      assert False, "Exception was raised: " + repr(ex)

    